require(knitr)
require(markdown)
require(sqldf)
require(ggplot2)
AirLineData <- read.table("part-r-00000", sep = "\t")
attach(AirLineData)
uniqueAirlines <- array(unique(AirLineData[,1]))
countUniqueAirlines <- length(uniqueAirlines)
singleAirLinedf <- sqldf(paste("select * FROM AirLineData where V1='",uniqueAirlines[1],"'",sep=""))
model_dist <- lm (singleAirLinedf$V5 ~ singleAirLinedf$V4)
sink("MyTppdf.pdf",append=TRUE,split=TRUE)
m <- mean(residuals(model_dist)^2)
m^(0.5)
