require(knitr)
require(markdown)
input = read.csv("TimeAnalysis.csv", sep=",",  col.names=c("Configuration","timeinmins"), strip.white=TRUE)
require(ggplot2)
graph <- qplot(data=input,x=Configuration,y=timeinmins)
png(filename="Time.png",800,800)
plot(graph)
dev.off()
knit('AnalysisReport.Rmd', 'Report.md')
markdownToHTML('Report.md', 'MyReport.html',option=c("use_xhml"))
system("pandoc -s MyReport.html -o MyReport.pdf")
